export type {
  AppSettings,
  CategoryKind,
  PresetPools,
  ReminderCategory,
  SubReminder,
  CountdownItem,
  PopupLayerTextEffects,
  PopupTheme,
  PopupThemeTarget,
  AppEntitlements,
  ResetIntervalPayload,
  TextTransform,
} from '../../shared/settings'

export {
  getStableDefaultCategories,
  getDefaultReminderCategories,
  getDefaultPresetPools,
  getDefaultPopupThemes,
  getDefaultEntitlements,
  defaultTextTransform,
  genId,
  SYSTEM_MAIN_POPUP_THEME_ID,
  SYSTEM_REST_POPUP_THEME_ID,
  BUILTIN_MAIN_POPUP_FALLBACK_BODY,
  BUILTIN_REST_POPUP_FALLBACK_BODY,
  mergeSystemBuiltinPopupThemes,
  getDefaultPopupThemeIdForTarget,
} from '../../shared/settings'
